# Generated by Django 5.0.7 on 2024-08-19 10:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KME',
            fields=[
                ('kme_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TrustedNode',
            fields=[
                ('trusted_node_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='KeyMaterial',
            fields=[
                ('key_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_value', models.CharField(max_length=512)),
                ('status', models.CharField(default='active', max_length=50)),
                ('kme_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quantum_app.kme')),
            ],
        ),
        migrations.CreateModel(
            name='SAE',
            fields=[
                ('sae_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('kme_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quantum_app.kme')),
            ],
        ),
    ]
