# Generated by Django 5.0.7 on 2024-09-20 05:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KME',
            fields=[
                ('kme_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_KME_ID', models.CharField(max_length=255)),
                ('target_KME_ID', models.CharField(max_length=255)),
                ('key_size', models.IntegerField(default=256)),
                ('stored_key_count', models.IntegerField(default=0)),
                ('max_key_count', models.IntegerField(default=100000)),
                ('max_key_per_request', models.IntegerField(default=128)),
                ('min_key_size', models.IntegerField(default=64)),
                ('max_key_size', models.IntegerField(default=1024)),
            ],
        ),
        migrations.CreateModel(
            name='KeyMaterial',
            fields=[
                ('key_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_value', models.CharField(max_length=512)),
                ('key_size', models.IntegerField(default=256)),
                ('status', models.CharField(default='active', max_length=50)),
                ('kme_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quantum_app.kme')),
            ],
        ),
        migrations.CreateModel(
            name='SAE',
            fields=[
                ('sae_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('kme_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quantum_app.kme')),
            ],
        ),
    ]
